### ISSUE TITLE
Host your blog on Netlify

### ISSUE THREAD

**Issue by DirtyF** [inwardmovement/inwardmovement.github.io#1]
Hi, 

I just browser the README, and you mention some issues with GitHub Pages, I just wanted you to know that you can get rid of these limitations if you connect your GitHub repo to [Netlify](https://netlify.com).

As soon as you'll commit on master on your repo, Netlify will trigger a build and publish your website on a ultra-fast CDN Network. Netlify offers tons of other features like custom HTTPS domain name.

I'd suggest you give it a try, it should solve some of your problems… for free. 🚀

**Comment by inwardmovement** [comment]
Hi Frank,

Yes I had Netlify in mind, I gave it a try but couldn't manage to make the deploy work. But I'm also interested in no custom domain name, this way I could cancel all my paid services at OVH 😄

Netlify could be a means to go beyond GitHub Pages' Jekyll limitations while still benefiting the "push source to deploy site" thing, so I may gave it another try, thanks!
